beta_start: 0.0001
beta_end: 0.01
timesteps: 20
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 1024
moving_avg: 25
factor: 3
distil: True
dropout: 0.05
activation: gelu
k_z: 0.01
k_cond: 1
p_hidden_dims: [64, 64]
CART_input_x_embed_dim: 32
p_hidden_layers: 2
d_z: 8
diffusion_config_dir: "./configs/nsdiff.yml"
sampling:
    batch_size: 256
    sampling_size: 1000
    last_only: True
    image_folder: 'sampling_image_samples'

testing:
    batch_size: 256
    sampling_size: 1000
    minisample: 1
    last_only: True
    plot_freq: 200
    n_z_samples: 100 
    n_z_samples_depart: 1 
    n_bins: 10
    compute_metric_all_steps: True
    mean_t: 0
    coverage_t: 0
    nll_t: 0
